import { Rate } from 'antd';


export const listProduct = [
    {
        id:1,
        image:'images/Image.png',
        name:'Coombes',
        category:'Lounge',
        collection:4,
        price:'$2,600',
        cart:'images/cart.png'
    },
     {
        id:2,
        image:'images/Image.png',
        name:'Coombes',
        category:'Lounge',
        collection:4,
        price:'$2,600',
        cart:'images/cart.png'
    },
     {
        id:3,
        image:'images/Image.png',
        name:'Coombes',
        category:'Lounge',
        collection:4,
        price:'$2,600',
        cart:'images/cart.png'
    },
     {
        id:4,
        image:'images/Image.png',
        name:'Coombes',
        category:'Lounge',
        collection:4,
        price:'$2,600',
        cart:'images/cart.png'
    },
     {
        id:5,
        image:'images/Image.png',
        name:'Coombes',
        category:'Lounge',
        collection:4,
        price:'$2,600',
        cart:'images/cart.png'
    },
     {
        id:6,
        image:'images/Image.png',
        name:'Coombes',
        category:'Lounge',
        collection:4,
        price:'$2,600',
        cart:'images/cart.png'
    },
     {
        id:7,
        image:'images/Image.png',
        name:'Coombes',
        category:'Lounge',
        collection:4,
        price:'$2,600',
        cart:'images/cart.png'
    }
]